name: Build N64 ROM

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dragonminded/libdragon:latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Audit Toolchain Bin
      run: |
        ls /n64_toolchain/bin

    - name: Build ROM
      run: make
           
    - name: Upload ROM
      uses: actions/upload-artifact@v4
      with:
        name: audio-test-rom
        path: '*.z64'
